; Listing generated by Microsoft (R) Optimizing Compiler Version 19.34.31937.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_01LFCBOECM@?4@				; `string'
PUBLIC	??_C@_0BH@GGFPJOFF@?5The?5fastest?5run?5took?5@	; `string'
PUBLIC	??_C@_0CB@IFKHNEHF@?5milliseconds?0?5the?5slowest?5took@ ; `string'
PUBLIC	??_C@_0BM@ECPJJEFK@?5seconds?0?5the?5slowest?5took?5@ ; `string'
PUBLIC	??_C@_0CE@POKBMHDB@?5failures?5for?5half?5a?5board?5of?5s@ ; `string'
PUBLIC	??_C@_0BA@LLNMHFLI@?5solutions?5and?5@		; `string'
PUBLIC	??_C@_0BF@DOJLFCKL@?5microseconds?0?5with?5@	; `string'
PUBLIC	??_C@_0BA@DMBECPMG@Resolving?5took?5@		; `string'
PUBLIC	??_C@_0CA@MJLLAPHA@Size?5must?5be?5at?5most?516?0?5it?5is?5@ ; `string'
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@I@Z:PROC
EXTRN	__imp__localtime64:PROC
EXTRN	__imp__time64:PROC
EXTRN	__imp_asctime:PROC
;	COMDAT ??_C@_0CA@MJLLAPHA@Size?5must?5be?5at?5most?516?0?5it?5is?5@
CONST	SEGMENT
??_C@_0CA@MJLLAPHA@Size?5must?5be?5at?5most?516?0?5it?5is?5@ DB 'Size mus'
	DB	't be at most 16, it is ', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@DMBECPMG@Resolving?5took?5@
CONST	SEGMENT
??_C@_0BA@DMBECPMG@Resolving?5took?5@ DB 'Resolving took ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@DOJLFCKL@?5microseconds?0?5with?5@
CONST	SEGMENT
??_C@_0BF@DOJLFCKL@?5microseconds?0?5with?5@ DB ' microseconds, with ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@LLNMHFLI@?5solutions?5and?5@
CONST	SEGMENT
??_C@_0BA@LLNMHFLI@?5solutions?5and?5@ DB ' solutions and ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CE@POKBMHDB@?5failures?5for?5half?5a?5board?5of?5s@
CONST	SEGMENT
??_C@_0CE@POKBMHDB@?5failures?5for?5half?5a?5board?5of?5s@ DB ' failures '
	DB	'for half a board of size ', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@ECPJJEFK@?5seconds?0?5the?5slowest?5took?5@
CONST	SEGMENT
??_C@_0BM@ECPJJEFK@?5seconds?0?5the?5slowest?5took?5@ DB ' seconds, the s'
	DB	'lowest took ', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CB@IFKHNEHF@?5milliseconds?0?5the?5slowest?5took@
CONST	SEGMENT
??_C@_0CB@IFKHNEHF@?5milliseconds?0?5the?5slowest?5took@ DB ' millisecond'
	DB	's, the slowest took ', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@GGFPJOFF@?5The?5fastest?5run?5took?5@
CONST	SEGMENT
??_C@_0BH@GGFPJOFF@?5The?5fastest?5run?5took?5@ DB ' The fastest run took'
	DB	' ', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_01LFCBOECM@?4@
CONST	SEGMENT
??_C@_01LFCBOECM@?4@ DB '.', 00H			; `string'
PUBLIC	??$pow@HH$0A@@@YANHH@Z				; pow<int,int,0>
PUBLIC	?do_solve@qns16@@YAXAEBT__m256i@@AEAV?$vector@HV?$allocator@H@std@@@std@@H@Z ; qns16::do_solve
PUBLIC	?threaten@qns16@@YA?BT__m256i@@AEBT2@HH@Z	; qns16::threaten
PUBLIC	?is_totally_under_threat@qns16@@YA_NAEBT__m256i@@H@Z ; qns16::is_totally_under_threat
PUBLIC	??Uqns16@@YA?AT__m256i@@AEBT1@0@Z		; qns16::operator|
PUBLIC	??Iqns16@@YA?AT__m256i@@AEBT1@0@Z		; qns16::operator&
PUBLIC	??8qns16@@YA_NAEBT__m256i@@0@Z			; qns16::operator==
PUBLIC	?set_board_size@qns16@@YAXH@Z			; qns16::set_board_size
PUBLIC	?test@qns16@@YAXXZ				; qns16::test
PUBLIC	?solve@qns16@@YANXZ				; qns16::solve
?success_count@qns16@@3IA DD 01H DUP (?)		; qns16::success_count
?threats@qns16@@3QBT__m256i@@B DB 02000H DUP (?)	; qns16::threats
?failures_count@qns16@@3IA DD 01H DUP (?)		; qns16::failures_count
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?do_solve@qns16@@YAXAEBT__m256i@@AEAV?$vector@HV?$allocator@H@std@@@std@@H@Z DD imagerel $LN83@do_solve
	DD	imagerel $LN83@do_solve+512
	DD	imagerel $unwind$?do_solve@qns16@@YAXAEBT__m256i@@AEAV?$vector@HV?$allocator@H@std@@@std@@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?threaten@qns16@@YA?BT__m256i@@AEBT2@HH@Z DD imagerel $LN6@threaten
	DD	imagerel $LN6@threaten+99
	DD	imagerel $unwind$?threaten@qns16@@YA?BT__m256i@@AEBT2@HH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Ethreats@qns16@@YAXXZ DD imagerel ??__Ethreats@qns16@@YAXXZ
	DD	imagerel ??__Ethreats@qns16@@YAXXZ+26636
	DD	imagerel $unwind$??__Ethreats@qns16@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?is_totally_under_threat@qns16@@YA_NAEBT__m256i@@H@Z DD imagerel $LN10@is_totally
	DD	imagerel $LN10@is_totally+115
	DD	imagerel $unwind$?is_totally_under_threat@qns16@@YA_NAEBT__m256i@@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??Uqns16@@YA?AT__m256i@@AEBT1@0@Z DD imagerel $LN4@operator
	DD	imagerel $LN4@operator+72
	DD	imagerel $unwind$??Uqns16@@YA?AT__m256i@@AEBT1@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??Iqns16@@YA?AT__m256i@@AEBT1@0@Z DD imagerel $LN4@operator
	DD	imagerel $LN4@operator+72
	DD	imagerel $unwind$??Iqns16@@YA?AT__m256i@@AEBT1@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?set_board_size@qns16@@YAXH@Z DD imagerel $LN7@set_board_
	DD	imagerel $LN7@set_board_+89
	DD	imagerel $unwind$?set_board_size@qns16@@YAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?test@qns16@@YAXXZ DD imagerel $LN24@test
	DD	imagerel $LN24@test+83
	DD	imagerel $unwind$?test@qns16@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?solve@qns16@@YANXZ DD imagerel $LN249@solve
	DD	imagerel $LN249@solve+1282
	DD	imagerel $unwind$?solve@qns16@@YANXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0??solve@qns16@@YANXZ@4HA DD imagerel ?dtor$0@?0??solve@qns16@@YANXZ@4HA
	DD	imagerel ?dtor$0@?0??solve@qns16@@YANXZ@4HA+36
	DD	imagerel $unwind$?dtor$0@?0??solve@qns16@@YANXZ@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$1@?0??solve@qns16@@YANXZ@4HA DD imagerel ?dtor$1@?0??solve@qns16@@YANXZ@4HA
	DD	imagerel ?dtor$1@?0??solve@qns16@@YANXZ@4HA+39
	DD	imagerel $unwind$?dtor$1@?0??solve@qns16@@YANXZ@4HA
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$1@?0??solve@qns16@@YANXZ@4HA DQ 0d004420800030801r ; -2.93214e+77
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0??solve@qns16@@YANXZ@4HA DQ 0d004420800030801r ; -2.93214e+77
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?solve@qns16@@YANXZ DQ 08a02050500022d0ar ; -1.83121e-260
	DD	02033904H
	DW	0641H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?solve@qns16@@YANXZ DW 0e04H
	DD	imagerel ?dtor$0@?0??solve@qns16@@YANXZ@4HA
	DB	02eH
	DD	imagerel ?dtor$1@?0??solve@qns16@@YANXZ@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?solve@qns16@@YANXZ DB 028H
	DD	imagerel $stateUnwindMap$?solve@qns16@@YANXZ
	DD	imagerel $ip2state$?solve@qns16@@YANXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?solve@qns16@@YANXZ DQ 0000ea83800175219r ; 2.03832e-308
	DQ	00010882e000f9833r		; 2.29905e-308
	DQ	00012682400117829r		; 2.55978e-308
	DQ	0002d641f002e741fr		; 8.17467e-308
	DQ	00026011f002c341fr		; 6.12017e-308
	DQ	0c012d014e016f018r		; -4.7032
	DD	05010H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?solve@qns16@@YANXZ
	DQ	00000004000000096r		; 1.35808e-312
	DD	020H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?test@qns16@@YAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?set_board_size@qns16@@YAXH@Z DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??Iqns16@@YA?AT__m256i@@AEBT1@0@Z DQ 05002720600020f01r ; 2.66979e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??Uqns16@@YA?AT__m256i@@AEBT1@0@Z DQ 05002720600020f01r ; 2.66979e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?is_totally_under_threat@qns16@@YA_NAEBT__m256i@@H@Z DQ 00002740a00040a01r ; 3.4117e-309
	DD	013405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Ethreats@qns16@@YAXXZ DQ 000096418000b1801r ; 1.30598e-308
	DQ	00007341800085418r		; 1.00177e-308
	DQ	0c012d014e016f018r		; -4.7032
	DD	07010H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?threaten@qns16@@YA?BT__m256i@@AEBT2@HH@Z DQ 05002720600020f01r ; 2.66979e+77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?do_solve@qns16@@YAXAEBT__m256i@@AEAV?$vector@HV?$allocator@H@std@@@std@@H@Z DQ 00012011200092919r ; 2.50379e-308
	DQ	07005c007e009f00br		; 4.22093e+231
	DQ	00000500230036004r		; 4.34631e-310
	DD	imagerel __GSHandlerCheck
	DQ	00000004000000044r		; 1.35808e-312
	DD	020H
?board_size@qns16@@3HA DD 010H				; qns16::board_size
?threats$initializer$@qns16@@3P6AXXZEA DQ FLAT:??__Ethreats@qns16@@YAXXZ ; qns16::threats$initializer$
END
